
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

zwave:
  usb_path: /dev/ttyUSB0

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
